#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_show_env 167 2023-01-12 10:03:18Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

TOOLLIST="awk sed grep host openssl curl wget git jq"
for tool in $TOOLLIST
do
	[ -x "$(type -p $tool)" ] || error 0 "WARNING: Tool \"$tool\" not available!"
done
showinfo "Effective settings:"
for VAR in ISM_VA ISM_FQDN ISM_IP ISM_USER ISM_session CACERT JSON
do
	printf "\t\t\t%-13s %s\n" "${VAR}:" "$(eval echo \$$VAR)"
done
