#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_show_racks 160 2022-12-21 16:16:17Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

CheckJQ
printf "RackId\tRackName\n"
printf "=======\t===============================\n"
ism_cmd get racks | jq -j '.IsmBody.Racks[]|.RackId,"\t",.Name,"\n"'
