#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_run_refreshnodes 160 2022-12-21 16:16:17Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

CheckJQ

showinfo "Reading node list ..."
ism_list_nodes $1 | jq -j '.IsmBody.Nodes[]|.NodeId," ",.IpAddress,"\n"' | \
	while read nodeid IP
	do
		[ $IP = null ] && continue || showinfo -n "BG refreshing NodeId $nodeid ($IP)"
		ism_cmd post nodes/$nodeid/inventory/refresh >/dev/null &
		echo "[PID=$!]"
done
