#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_show_env 152 2022-12-18 12:03:18Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

[ -x "$(type -p jq)" ] || error 0 "WARNING: Tool \"jq\" not available!"
showinfo "Effective settings:"
for VAR in ISM_VA ISM_FQDN ISM_IP ISM_USER ISM_session CACERT JSON
do
	printf "\t\t\t%-13s %s\n" "${VAR}:" "$(eval echo \$$VAR)"
done
