#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_show_isos 158 2022-12-18 17:32:48Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

CheckJQ

echo -e " ID\tFilename"
echo -e "===\t=============================="
ism_cmd get system/settings/repositories/profiles |\
	jq -j '.IsmBody.RepositoryList[]|.RepositoryId,"\t",.FileName,"\n"' 
