#!/bin/bash
# (c) Gerald Rausch
# $Id: ism_set_power 168 2023-02-11 09:05:45Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env


[ "$#" -ne 2 ] && error 1 "exactly two arguments necessary - `basename $0` <serialnumber>|<ip>|<name> PowerOn|Shutdown"

case "${2,,}" in
	poweron)	NEWSTATE=PowerOn;;
	shutdown)	NEWSTATE=Shutdown;;
	*)		error 1 "<$2> Unknown Argument - the second parameter is wrong, use --> (PowerOn or ShutDown)!"
esac

ism_cmd patch nodes/$(ism_get_nodeid $1)/power -d "{ \"IsmBody\": { \"Parts\": [ {\"Name\": \"PowerManagement\",\"PowerStatus\": \"${NEWSTATE}\" } ] } }"  | $JSON
