#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_del_iso 158 2022-12-18 17:32:48Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

CheckJQ

echo " ID Filename"
echo "=== =============================="
ism_cmd get system/settings/repositories/profiles |\
	jq -j '.IsmBody.RepositoryList[]|.RepositoryId,"\t",.FileName,"\n"' |\
		while read id filename 
		do
			iso[$id]=$filename
			printf "%3d %s\n" $id $filename
		done 

ID=$1
while [ "${iso[$ID]}" == "" ]
do
	echo -n "Please enter ID that should be deleted: "
	read ID
	[ "${iso[$ID]}" ] ||  echo invalid ID - Try again
done
echo "Deleting ${iso[$ID]} ..."
ism_cmd delete system/settings/repositories/profiles/$ID -d '{"IsmBody": null}'

