#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_copy_2ds 170 2023-02-28 10:34:26Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

DS_INT=datastore.fsc.net
DS_EXT=datastore.ts.fujitsu.com
host $DS_INT >/dev/null && DATASTORE=$DS_INT || DATASTORE=$DS_EXT
ANON=anonymous
PW=ftp
DIR=incoming

[ -x "$(type -p sshpass)" ] && SCP="sshpass -p $PW scp" || { SCP=scp; showinfo "If required enter \"$PW\" as password"; }

[ -r "$1" ] || error 1 "At least ne filename should be given as argument!"

for file in "$@"
do
	showinfo "Transferring $file to ${DATASTORE}:/${DIR}/${file##*/}"
	$SCP -q "$file" ${ANON}@${DATASTORE}:/${DIR}/ 2>/dev/null
	showinfo "  done"
done
