#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_del_iso 170 2023-02-28 10:34:26Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

CheckJQ

echo " ID Filename"
echo "=== =============================="
while read id filename 
do
	iso[$id]=$filename
	printf "%3d %s\n" $id $filename
done < <(ism_cmd get system/settings/repositories/profiles | \
	jq -j '.IsmBody.RepositoryList[]|.RepositoryId,"\t",.FileName,"\n"')

ID=$1
while [ "${iso[$ID]}" == "" ]
do
	echo -n "Please enter ID that should be deleted (or q to quit): "
	read ID
	[ "$ID" = q ] && exit
	[ "${iso[$ID]}" ] ||  echo invalid ID - Try again
done
echo "Deleting ${iso[$ID]} ..."
ism_cmd delete system/settings/repositories/profiles/$ID -d '{"IsmBody": null}'

