#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_list_events 152 2022-12-18 12:03:18Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env
[ "$1" ] || error 1 "One param is needed (IP, Name or S/N)!"

ism_cmd get 'event/history/event/show/?resourceidtype=NodeId&resourceid='"$(ism_get_nodeid $1)"'' | $JSON
