#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_logout 152 2022-12-18 12:03:18Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

if [ "$ISM_session" ]
then
	ism_cmd post users/logout -d "{}" >/dev/null
	echo unset ISM_session
else
	error 1 "No ISM_session set"
fi
