#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_list_traps 160 2022-12-21 16:16:17Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

[ "$1" ] || error 1 "One param is needed (IP, Name or S/N)!"

ism_cmd get "event/history/trap?Resourcetype=NodeId&resourceid=$(ism_get_nodeid $1)" | $JSON
