#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_list_nodes 152 2022-12-18 12:03:18Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

# Filter can be: name, type, model, ipaddress, rackid, floorid, dcid, nodegroupid, status, alarmstatus, nodetag, uniqinfo
FILTER="${1}"
ism_cmd get "nodes?${FILTER}" | $JSON
