#!/bin/bash
# (c) Gerald Rausch ;-)
# $Id: ism_show_cpu_mem 178 2025-06-25 10:19:43Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools

. ${0%/*}/.ism_env

CheckJQ

listCpu()
{
	# table header
	echo '"Node","Serial","CPU-Socket","Model","Cores"'
	
	while read id nodename serial
	do
 		ism_cmd get "nodes/$id/inventory?" |jq -r '.IsmBody.Node.VariableData.Cpus' | jq --arg node $nodename -r  --arg Serial $serial '(.[] | [$node, $Serial, .Name, .Model, .Core]) | @csv '
	done < <(ism_cmd get /nodes?type=server | jq -j '.IsmBody.Nodes[]|.NodeId," ",.Name," ",.UniqInfo,"\n"')
}


listMem()
{
	# table header
	echo '"Node","Serial","MEM-Socket","MemorySize","Frequency"'
	
	while read id nodename serial
	do
 		ism_cmd get "nodes/$id/inventory?" |jq -r '.IsmBody.Node.VariableData.MemoryModules' | jq --arg node $nodename -r  --arg Serial $serial '(.[] | [$node, $Serial, .Name, .MemorySize, .Frequency]) | @csv '
	done < <(ism_cmd get /nodes?type=server | jq -j '.IsmBody.Nodes[]|.NodeId," ",.Name," ",.UniqInfo,"\n"')
}

[ "$#" -ne 1 ] && error 1 "exactly one argument necessary - `basename $0` <cpu>|<mem>"

case "${1,,}" in
        cpu)        listCpu;;
        mem)        listMem;;
        *)              error 1 "<$1> Unknown Argument - the first parameter is wrong, use --> (cpu or mem)!"
esac

