#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_get_nodeid 152 2022-12-18 12:03:18Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools
#
# Gets NodeId for IP-Address or NodeName or S/N in $1 
#

. ${0%/*}/.ism_env

CheckJQ
[ "$1" ] || error 1 "One param is needed (IP, Name or S/N)!"

ism_cmd get nodes | jq --arg param $1 '.IsmBody.Nodes[]|
  select(.IpAddress==$param or .Name==$param or .UniqInfo==$param)|.NodeId'
