#!/bin/bash
# (c) Juergen Orth ;-)
# $Id: ism_cmd 162 2023-01-05 17:56:44Z HMBJOrth $
# for documentation see https://github.com/fujitsu/ISMtools
#
# ism_cmd: Perform basic REST calls with GET, POST, DELETE, PATCH, ..
#

. ${0%/*}/.ism_env

[ "$DEBUG" -gt 2 ] && set -x

METHOD=${1:-GET}
CMD=${2:-'nodes'}; shift 2

[ -r "$CACERT" ] && CERTOPT="--cacert $CACERT" || { CERTOPT="-k"; [ "$WARNING" ] && error  0 "unsecure mode!"; }

if [ "$ISM_session" ]
then
	# With Session ID (you have to run "eval $(ism_login)" before running this script and afterwards "eval $(ism_logout)")
	AUTH="X-Ism-Authorization: $ISM_session"
else
	# w/o Session ID = One Time Authorization
	AUTH="Authorization: ISM $(ism_enc_pw $ISM_USER)"
fi

debugmsg 1 $METHOD $CMD
curl "https://${ISM_VA}/ism/api/v2/$CMD" -X ${METHOD^^} -H "$AUTH" -H "Content-Type: application/JSON; charset=UTF-8" $CERTOPT $CURLOPTIONS "$@"
echo
